version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - aws s3 sync . s3://rentaportablesink.com
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - index.html
  discard-paths: no
